CREATE DATABASE CASE_STATEMENT;
USE CASE_STATEMENT;

CREATE TABLE IF NOT EXISTS student (
	Subject VARCHAR(30)
);

INSERT INTO Student VALUES ("Computer"),("B.Tech"),("History"),("BA");

SELECT * FROM Student;

/* CASE STATEMENT */
DELIMITER $$
CREATE PROCEDURE Student_Case(IN S_Sub VARCHAR(30), OUT S_Course VARCHAR(30))
BEGIN 
	DECLARE sub VARCHAR (20);
    SELECT subject INTO sub FROM Student WHERE subject = S_Sub;
    CASE sub
		WHEN 'Computer' THEN 
			SET S_Course = 'B.Tech';
		WHEN 'History' THEN 
			SET S_Course = 'BA';
		ELSE 
			SET S_Course = 'Subject is not available';
	END CASE;
END$$
DELIMITER ;

CALL Student_Case('Computer',@S_Course);
SELECT @S_Course;
CALL Student_Case('History',@S_Course);
SELECT @S_Course;
CALL Student_Case('Economics',@S_Course);
SELECT @S_Course;

											-- EXAMPLES OF CASE STATEMENT --

CREATE TABLE IF NOT EXISTS STUDENTS_GRADES(
ID INT AUTO_INCREMENT,
`NAME` VARCHAR(30),
SCORE VARCHAR(30),
PRIMARY KEY(ID)
);

INSERT INTO STUDENTS_GRADES (`NAME`, SCORE)
VALUES ('Simisola', 60), ('Ivan', 80), ('Metodija', 52), ('Callum', 98), ('Leia', 84),
       ('Aparecida', 82), ('Ursula', 69), ('Ramazan', 78), ('Corona', 87), ('Alise', 57),
       ('Galadriel', 89), ('Merel', 99), ('Cherice', 55), ('Nithya', 81), ('Elsad', 71),
       ('Liisi', 90), ('Johanna', 90), ('Anfisa', 90), ('Ryōsuke', 97), ('Sakchai', 61),
       ('Elbert', 63), ('Katelyn', 51);
       
SELECT * FROM STUDENTS_GRADES;

/* CASE STATEMENT */
/* GRADE */
SELECT *,
	CASE
		WHEN SCORE >= 94 THEN "A"
        WHEN SCORE >= 90 THEN "A-"
        WHEN SCORE >= 87 THEN "B+"
        WHEN SCORE >= 83 THEN "B"
        WHEN SCORE >= 80 THEN "B-"
        WHEN SCORE >= 77 THEN "C+"
        WHEN SCORE >= 73 THEN "C"
        WHEN SCORE >= 70 THEN "C-"
        WHEN SCORE >= 67 THEN "D+"
        WHEN SCORE >= 60 THEN "D"
        ELSE "F"
	END AS GRADE
FROM STUDENTS_GRADES ORDER BY SCORE DESC;

/* COUNT OF STUDENTS */
SELECT
	CASE 
		WHEN SCORE >= 94 THEN "A"
        WHEN SCORE >= 90 THEN "A-"
        WHEN SCORE >= 87 THEN "B+"
        WHEN SCORE >= 83 THEN "B"
        WHEN SCORE >= 80 THEN "B-"
        WHEN SCORE >= 77 THEN "C+"
        WHEN SCORE >= 73 THEN "C"
        WHEN SCORE >= 70 THEN "C-"
        WHEN SCORE >= 67 THEN "D+"
        WHEN SCORE >= 60 THEN "D"
        ELSE "F"
	END AS GRADE,
    COUNT(*) AS NUMBER_OF_STUDENTS
FROM STUDENTS_GRADES
GROUP BY GRADE
ORDER BY
	CASE 
		WHEN GRADE = 'A' THEN 1
		WHEN GRADE = 'A-' THEN 2
        WHEN GRADE = 'B+' THEN 3
        WHEN GRADE = 'B' THEN 4
        WHEN GRADE = 'B-' THEN 5
        WHEN GRADE = 'C+' THEN 6
        WHEN GRADE = 'C' THEN 7
        WHEN GRADE = 'C-' THEN 8
        WHEN GRADE = 'D+' THEN 9
        WHEN GRADE = 'D-' THEN 10
        ELSE 11
	END;

/* PASS OR FAIL */
SELECT
	CASE 
		WHEN score >= 60
			THEN "Passed"
		ELSE "Failed"
	END AS Result,
	COUNT(*) AS Number_of_Students
FROM Students_Grades
GROUP BY Result
ORDER BY Result DESC;


-- NEW FILE LOADED Top Schools Delhi Schools Directory Dummy.csv FOR CASE Statement --

CREATE TABLE IF NOT EXISTS SCHOOL_DETAILS (`NAME` VARCHAR(50), LOCATION VARCHAR(50), PHONE_NO_Email_Address VARCHAR(255));

LOAD DATA INFILE "F:/BIT TRAINING/MySQL/Top-Schools-Delhi-Schools-Directory-Dummy.csv"
INTO TABLE SCHOOL_DETAILS
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(`NAME`, LOCATION, PHONE_NO_Email_Address);

SELECT * FROM School_Details;

ALTER TABLE SCHOOL_DETAILS
ADD COLUMN MOBILE_NO VARCHAR(20) AFTER PHONE_NO_EMAIL_Address,
ADD COLUMN EMAIL_ADDRESS VARCHAR(100) AFTER PHONE_NO_EMAIL_Address;

UPDATE SCHOOL_DETAILS
SET	
	MOBILE_NO = CASE 
		WHEN PHONE_NO_Email_Address NOT LIKE '%@%' THEN PHONE_NO_Email_Address
        ELSE NULL 
	END,
    EMAIL_ADDRESS = CASE 
		WHEN PHONE_NO_Email_Address LIKE '%@%' THEN PHONE_NO_Email_Address
        ELSE NULL 
	END;

SELECT `NAME`, LOCATION,
GROUP_CONCAT(CASE WHEN MOBILE_NO IS NOT NULL THEN MOBILE_NO END) AS MOBILE_NO,
GROUP_CONCAT(CASE WHEN EMAIL_ADDRESS IS NOT NULL THEN EMAIL_ADDRESS END) AS EMAIL_ADDRESS
FROM SCHOOL_DETAILS
GROUP BY `NAME`, LOCATION;

-- Another Way of Loading Data Right Click on DATABASE or TABLES and SELECT DATA TABLE IMPORT WIZARD --

SELECT * FROM School_Details_2;

									
                                    
                                    -- CASE STATEMENT FOR DATA CLEANING EXAMPLES --

-- (1) Split City and State From Full Address --

CREATE TABLE IF NOT EXISTS CUSTOMER_DETAILS (
	CUSTOMER_NAME VARCHAR(100),
	FULL_ADDRESS VARCHAR(100)
);

INSERT INTO CUSTOMER_DETAILS VALUES
('Ankit Shamra', 'Mumbai, Maharashtra'),
('Pooja Rani', 'Delhi, Delhi'),
('Raj Mehta', 'Bangalore, Karnataka'),
('Alok Jain', 'Kolkata, West Bengal');

SELECT * FROM CUSTOMER_DETAILS;

ALTER TABLE CUSTOMER_DETAILS
ADD COLUMN CITY VARCHAR(50),
ADD COLUMN STATE VARCHAR(50);

SELECT(CASE 
WHEN FULL_ADDRESS LIKE '%,%' 
THEN SUBSTRING_INDEX(FULL_ADDRESS, ',',1)
ELSE FULL_ADDRESS 
END) 
AS CITY FROM CUSTOMER_DETAILS;

SELECT(CASE 
WHEN FULL_ADDRESS LIKE '%,%' 
THEN SUBSTRING_INDEX(FULL_ADDRESS, ',',-1)
ELSE FULL_ADDRESS 
END) 
AS STATE FROM CUSTOMER_DETAILS;

UPDATE CUSTOMER_DETAILS
SET 
	CITY = CASE 
    WHEN FULL_ADDRESS LIKE '%,%' THEN SUBSTRING_INDEX(FULL_ADDRESS, ',',1)
	ELSE FULL_ADDRESS
    END,
	STATE = CASE 
    WHEN FULL_ADDRESS LIKE '%,%' THEN SUBSTRING_INDEX(FULL_ADDRESS, ',',-1)
	ELSE FULL_ADDRESS
END; 


SELECT * FROM CUSTOMER_DETAILS;

CREATE TABLE IF NOT EXISTS CUSTOMER_DETAILS2 (
	CUSTOMER_NAME VARCHAR(100),
    FULL_ADDRESS VARCHAR(100)
);

INSERT INTO CUSTOMER_DETAILS2 VALUES
('Ankit Shamra', 'Boriwali West,Mumbai, Maharashtra'),
('Pooja Rani', 'Chandni Chowk,Delhi, Delhi'),
('Raj Mehta', 'xyz,Bangalore, Karnataka'),
('Alok Jain', 'xyz,Kolkata, West Bengal, West Bengal');

ALTER TABLE CUSTOMER_DETAILS2
ADD COLUMN CITY VARCHAR(50),
ADD COLUMN STATE VARCHAR(50);

SELECT * FROM CUSTOMER_DETAILS2;

UPDATE CUSTOMER_DETAILS2
SET 
	CITY = CASE
    -- NEW FORMAT WITH TWO COMMAS
    WHEN FULL_ADDRESS LIKE '%,%,%'THEN TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(FULL_ADDRESS, ',', 2),',',-1))
    -- OLD FORMAT WITH ONE COMMA
    WHEN FULL_ADDRESS LIKE '%,%' THEN TRIM(SUBSTRING_INDEX(FULL_ADDRESS,',',1))
    ELSE NULL
END,
	STATE = CASE
    -- ALWAYS EXTRACT THE LAST PART AS STATE
    	WHEN FULL_ADDRESS LIKE '%,%' THEN TRIM(SUBSTRING_INDEX(FULL_ADDRESS,',',-1))
    ELSE NULL
END;

SELECT * FROM CUSTOMER_DETAILS2;

-- without Using CASE 

ALTER TABLE CUSTOMER_DETAILS2
ADD COLUMN CITY_without_Case VARCHAR(50),
ADD COLUMN STATE_without_Case VARCHAR(50);


UPDATE CUSTOMER_DETAILS2
SET 
	CITY_without_Case = TRIM(
		SUBSTRING_INDEX(SUBSTRING_INDEX(FULL_ADDRESS,',',2),',',-1)),
	STATE_without_Case = TRIM(
		SUBSTRING_INDEX(FULL_ADDRESS,',',-1));

-- CLEAN PHONE NUMBERS AND SEPARATE MOBILE FROM LANDLINE --

CREATE TABLE IF NOT EXISTS CONTACTS (
PERSON_NAME VARCHAR(100),
CONTACT_INFO VARCHAR(50)
);

INSERT INTO CONTACTS VALUES
('Ravi Kumar', '9876543210'),
('Sonia Verma', '011-2256789'),
('Manish Gupta', '9123456789'),
('Neha Roy', '033-1234567');

SELECT * FROM CONTACTS;

ALTER TABLE CONTACTS
ADD COLUMN MOBILE_NO VARCHAR(20),
ADD COLUMN LANDLINE_NO VARCHAR(20);

UPDATE CONTACTS
SET
	MOBILE_NO = CASE 
    WHEN CONTACT_INFO REGEXP '^[7-9][0-9]{9}$' THEN CONTACT_INFO
    ELSE NULL
   END,
	LANDLINE_NO = CASE
	WHEN CONTACT_INFO NOT REGEXP '^[7-9][0-9]{9}$' THEN CONTACT_INFO
    ELSE NULL 
    END;

SELECT * FROM CONTACTS;

CREATE TABLE IF NOT EXISTS VEHICLE_NUMBER (
    `NAME` VARCHAR(50),
    DETAILS VARCHAR(100)
);

INSERT INTO VEHICLE_NUMBER VALUES
('TIRTH MODI', 'TheVehicleNumberIsGJ06DP6970anditwasregisteredingujarat');

SELECT * FROM VEHICLE_NUMBER;

ALTER TABLE VEHICLE_NUMBER
ADD COLUMN RTO_NUMBER VARCHAR(20);

SELECT REGEXP_SUBSTR(DETAILS,'[A-Z]{2}[0-9]{2}[A-Z]{1,2}[0-9]{4}') AS Vehicle_Number FROM VEHICLE_NUMBER;

UPDATE VEHICLE_NUMBER
SET
RTO_NUMBER = CASE
WHEN DETAILS REGEXP '[A-Z]{2}[0-9]{2}[A-Z]{1,2}[0-9]{4}'
THEN REGEXP_SUBSTR(DETAILS,'[A-Z]{2}[0-9]{2}[A-Z]{1,2}[0-9]{4}')
ELSE NULL
END;

SELECT * FROM VEHICLE_NUMBER;


-- Extract Email Domain --

CREATE TABLE IF NOT EXISTS EMAILS (
    USER_NAME VARCHAR(50),
    EMAIL VARCHAR(100)
);

INSERT INTO EMAILS VALUES
('Arjun', 'arjun123@gmail.com'),
('Sita', 'sita_01@yahoo.com'),
('Ram', 'ram@company.co.in'),
('Lakshmi', 'lakshmi99@rediffmail.com');

SELECT * FROM EMAILS;

ALTER TABLE EMAILS
ADD COLUMN EMAIL_DOMAIN VARCHAR(50);

UPDATE EMAILS 
SET EMAIL_DOMAIN = CASE 
	WHEN EMAIL LIKE '%@%' THEN SUBSTRING_INDEX(EMAIL,'@',-1)
    ELSE NULL
END;

SELECT * FROM EMAILS;

-- Standardize Inconsistent Category Names --

CREATE TABLE IF NOT EXISTS PRODUCT_INFO (
	PRODUCT_ID INT,
    CATEGORY_NAME VARCHAR(50)
);

INSERT INTO PRODUCT_INFO VALUES
(1, 'Mobiles'),
(2, 'Mobile Phones'),
(3, 'Laptops'),
(4, 'Notebook'),
(5, 'Smartphones'),
(6, 'Laptop');

SELECT * FROM PRODUCT_INFO;

UPDATE PRODUCT_INFO 
SET CATEGORY_NAME = CASE 
	WHEN CATEGORY_NAME IN ('Mobiles','Mobile Phones','Smartphones') THEN 'MOBILE'
    WHEN CATEGORY_NAME IN ('Laptop','Notebook','Laptops') THEN 'Laptop'
    ELSE CATEGORY_NAME
END;

SELECT * FROM PRODUCT_INFO;

-- MARK RECORDS AS VALID OR INVALID --

CREATE TABLE IF NOT EXISTS APPLICATIONS (
	APP_ID INT,
    EMAIL_ID VARCHAR(200),
    PHONE VARCHAR(20)
);

INSERT INTO APPLICATIONS VALUES
(1, 'applicant1@gmail.com', '9876543210'),
(2, 'no-email', '2345'),
(3, 'user2@yahoo.com', '9123456789'),
(4, 'wrongemail', 'landline-123');

SELECT * FROM APPLICATIONS;

ALTER TABLE APPLICATIONS
ADD COLUMN DATA_VALIDITY_STATUS VARCHAR(10);

UPDATE APPLICATIONS
SET DATA_VALIDITY_STATUS = CASE
    WHEN EMAIL_ID LIKE '%@%' AND PHONE REGEXP '^[7-9][0-9]{9}$' THEN 'VALID'
    ELSE 'INVALID'
END;

SELECT * FROM APPLICATIONS;

-- Standardize Gender Field --

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID INT,
    GENDER VARCHAR(20)
);

INSERT INTO USERS VALUES
(1, 'M'),
(2, 'FEMALE'),
(3, 'f'),
(4, 'MALE'),
(5, 'Unknown'),
(6, 'F');

SELECT * FROM USERS;

UPDATE USERS
SET GENDER = CASE 
	WHEN UPPER(GENDER) IN ('M','MALE') THEN 'Male' 
	WHEN UPPER(GENDER) IN ('F','FEMALE') THEN 'Female'
    ELSE 'Other'
END;

SELECT * FROM USERS;

-- Flag Null or Missing Values --

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID INT,
    CUSTOMER_NAME VARCHAR(100)
);

INSERT INTO ORDERS VALUES
(101, 'Amit'),
(102, NULL),
(103, 'Rhea'),
(104, ''),
(105, 'Raj');

SELECT * FROM ORDERS;

UPDATE ORDERS
SET CUSTOMER_NAME = CASE 
	WHEN CUSTOMER_NAME IS NULL OR TRIM(CUSTOMER_NAME) = '' THEN 'MISSING'
    ELSE CUSTOMER_NAME
END;

SELECT * FROM ORDERS;

-- Convert Timestamps to Time of Day Segments --

CREATE TABLE IF NOT EXISTS LOGIN_LOGS (
    USER_ID INT,
    LOGIN_TIME TIME
);

INSERT INTO LOGIN_LOGS VALUES
(1, '08:15:00'),
(2, '14:30:00'),
(3, '19:45:00'),
(4, '23:10:00');

SELECT * FROM LOGIN_LOGS;

ALTER TABLE LOGIN_LOGS
ADD COLUMN LOGIN_PERIOD VARCHAR(20);

UPDATE LOGIN_LOGS
SET LOGIN_PERIOD = CASE 
    WHEN HOUR(LOGIN_TIME) BETWEEN 5 AND 11 THEN 'Morning'
    WHEN HOUR(LOGIN_TIME) BETWEEN 12 AND 17 THEN 'Afternoon'
    WHEN HOUR(LOGIN_TIME) BETWEEN 18 AND 21 THEN 'Evening'
    ELSE 'Night'
END;

SELECT * FROM LOGIN_LOGS;


-- Validate Website URLs --

CREATE TABLE IF NOT EXISTS COMPANY_WEB (
    COMPANY_ID INT,
    WEBSITE VARCHAR(100)
);

INSERT INTO COMPANY_WEB VALUES
(1, 'http://example.com'),
(2, 'https://company.in'),
(3, 'company.org'),
(4, ''),
(5, NULL);

SELECT * FROM COMPANY_WEB;

ALTER TABLE COMPANY_WEB
ADD COLUMN URL_STATUS VARCHAR(10);

UPDATE COMPANY_WEB
SET URL_STATUS = CASE 
	WHEN WEBSITE LIKE 'http%' THEN 'VALID'
    ELSE 'INVALID'
END;

SELECT * FROM COMPANY_WEB;


-- Extract and Normalize Address Components --

CREATE TABLE ADDRESS_DATA (
    ID INT,
    FULL_ADDRESS VARCHAR(255)
);

INSERT INTO ADDRESS_DATA VALUES
(1, 'Delhi, Delhi - 110001'),
(2, 'Mumbai, Maharashtra - 400001'),
(3, 'Bangalore - 560001, Karnataka'),
(4, 'Chennai Tamil Nadu 600001'),
(5, 'Kolkata, West Bengal -700001');

SELECT * FROM ADDRESS_DATA;

ALTER TABLE ADDRESS_DATA
ADD COLUMN CITY VARCHAR(50),
ADD COLUMN STATE VARCHAR(50),
ADD COLUMN PIN_CODE VARCHAR(10);

SELECT (CASE 
	WHEN FULL_ADDRESS REGEXP '[0-9]{6}$' THEN SUBSTRING(FULL_ADDRESS,LENGTH(FULL_ADDRESS) - 5, 6)
	WHEN FULL_ADDRESS REGEXP '[0-9]{6}' THEN SUBSTRING(FULL_ADDRESS,LOCATE('-',FULL_ADDRESS)+2, 6)
    ELSE null 
END) AS PIN_CODE FROM ADDRESS_DATA;

UPDATE ADDRESS_DATA
SET PIN_CODE = CASE 
	WHEN FULL_ADDRESS REGEXP '[0-9]{6}$' THEN SUBSTRING(FULL_ADDRESS,LENGTH(FULL_ADDRESS) - 5, 6)
	WHEN FULL_ADDRESS REGEXP '[0-9]{6}' THEN SUBSTRING(FULL_ADDRESS,LOCATE('-',FULL_ADDRESS)+2, 6)
    ELSE null 
END,
CITY = CASE
    WHEN FULL_ADDRESS LIKE '%,%' THEN TRIM(SUBSTRING_INDEX(FULL_ADDRESS, ',', 1))
    WHEN FULL_ADDRESS LIKE '%-%' THEN TRIM(SUBSTRING_INDEX(FULL_ADDRESS, '-', 1))
    ELSE TRIM(SUBSTRING_INDEX(FULL_ADDRESS, ' ', 1))
END,
STATE = CASE 
	WHEN FULL_ADDRESS LIKE '%,%' THEN TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(FULL_ADDRESS, ',', -1),'-',1))
    WHEN FULL_ADDRESS LIKE '%-%' THEN TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(FULL_ADDRESS, '-', -1),',',-1))
    ELSE TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(FULL_ADDRESS, ' ', -3),' ',2))
END;

SELECT * FROM ADDRESS_DATA;

SELECT (CASE
    WHEN FULL_ADDRESS LIKE '%,%' THEN TRIM(SUBSTRING_INDEX(FULL_ADDRESS, ',', 1))
    WHEN FULL_ADDRESS LIKE '%-%' THEN TRIM(SUBSTRING_INDEX(FULL_ADDRESS, '-', 1))
    ELSE TRIM(SUBSTRING_INDEX(FULL_ADDRESS, ' ', 1))
END) AS CITY FROM ADDRESS_DATA;

SELECT (CASE
	WHEN FULL_ADDRESS LIKE '%,%' THEN TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(FULL_ADDRESS, ',', -1),'-',1))
    WHEN FULL_ADDRESS LIKE '%-%' THEN TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(FULL_ADDRESS, '-', -1),',',-1))
    ELSE TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(FULL_ADDRESS, ' ', -3),' ',2))
END) AS STATE FROM ADDRESS_DATA;
