CREATE DATABASE SALES;
USE SALES;

CREATE TABLE SALES1(
	ORDER_ID VARCHAR(15) NOT NULL,
    ORDER_DATE VARCHAR(15) NOT NULL,
    SHIP_DATE VARCHAR (15) NOT NULL,
    SHIP_MODE VARCHAR(14) NOT NULL,
    CUSTOMER_NAME VARCHAR(22) NOT NULL,
    SEGMENT VARCHAR(11) NOT NULL,
    STATE VARCHAR(36) NOT NULL,
    COUNTRY VARCHAR(32) NOT NULL,
    MARKET VARCHAR(6) NOT NULL,
    REGION VARCHAR(14) NOT NULL,
    PRODUCT_ID VARCHAR(16) NOT NULL,
    CATEGORY VARCHAR(15) NOT NULL,
    SUB_CATEGORY VARCHAR(11) NOT NULL,
    PRODUCT_NAME VARCHAR(127) NOT NULL,
    SALES DECIMAL(38,0) NOT NULL,
    QUANTITY DECIMAL(38,0) NOT NULL,
    DISCOUNT DECIMAL(38,3) NOT NULL,
    PROFIT DECIMAL(38,8) NOT NULL,
    SHIPPING_COST DECIMAL(38,2) NOT NULL,
    ORDER_PRIORITY VARCHAR(8) NOT NULL,
    `YEAR` DECIMAL(38,0) NOT NULL
);

SET SESSION SQL_MODE = '';

LOAD DATA INFILE
"F:/sales_data_final.csv"      
INTO TABLE SALES1
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM SALES1;

SET SQL_SAFE_UPDATES = 0;

## mm/dd/yyyy to yyyy-mm-dd

/*
d- 29
m- 12
b- Dec
M- December
y- 25
Y- 2025
*/

SELECT STR_TO_DATE(ORDER_DATE,'%m/%d/%Y') FROM SALES1;

ALTER table SALES1
ADD COLUMN ORDER_DATE_NEW DATE AFTER ORDER_DATE;

UPDATE SALES1
SET ORDER_DATE_NEW = STR_TO_DATE(ORDER_DATE,'%m/%d/%Y');

SELECT * FROM SALES1;

ALTER table SALES1
ADD COLUMN SHIP_DATE_NEW DATE AFTER SHIP_DATE;

UPDATE SALES1
SET SHIP_DATE_NEW = STR_TO_DATE(SHIP_DATE,'%m/%d/%Y');

SELECT date_format(ORDER_DATE_NEW,'%d/%m/%Y') FROM SALES1;

SELECT NOW();

SELECT CURDATE();

SELECT CURTIME();

ALTER TABLE SALES1
ADD COLUMN FLAG1 DATE AFTER ORDER_ID;

SELECT * FROM SALES1;

UPDATE SALES1
SET FLAG1 = NOW();

ALTER TABLE SALES1
ADD COLUMN DAY_NEW INT;

ALTER TABLE SALES1
ADD COLUMN MONTH_NEW INT;

ALTER TABLE SALES1
ADD COLUMN YEAR_NEW INT;

UPDATE SALES1 SET MONTH_NEW = MONTH(ORDER_DATE_NEW);
UPDATE SALES1 SET DAY_NEW = DAY(ORDER_DATE_NEW);
UPDATE SALES1 SET YEAR_NEW = YEAR(ORDER_DATE_NEW);

SELECT * FROM SALES1;

SELECT * FROM SALES1 WHERE SHIP_DATE_NEW = '2011-01-06';

SELECT * FROM SALES1 WHERE SHIP_DATE_NEW > '2011-01-06';

SELECT * FROM SALES1 WHERE SHIP_DATE_NEW < '2011-01-06';

SELECT * FROM SALES1 WHERE SHIP_DATE_NEW BETWEEN '2011-01-05'AND "2011-02-05";

SELECT YEAR_NEW, avg(SALES) FROM SALES1 GROUP BY YEAR_NEW;

SELECT YEAR_NEW,MONTH_NEW, sum(SALES) FROM SALES1 GROUP BY YEAR_NEW,MONTH_NEW;

SELECT YEAR_NEW, MIN(SALES) FROM SALES1 GROUP BY YEAR_NEW;

SELECT YEAR_NEW, MAX(SALES) FROM SALES1 GROUP BY YEAR_NEW;

SELECT SUM(SALES*DISCOUNT+SHIPPING_COST) AS CTC, YEAR_NEW FROM SALES1 GROUP BY YEAR_NEW;

SELECT ORDER_ID,DISCOUNT, IF(DISCOUNT > 0, 'YES', 'NO') AS DISCOUNT_FLAG FROM SALES1;

SELECT COUNTRY,SALES, IF(SALES > 100, 'YES', 'NO') AS BEST_SALE FROM SALES1;

SELECT SALES,QUANTITY,DISCOUNT,SHIPPING_COST, (SALES*QUANTITY*DISCOUNT+SHIPPING_COST) AS CTC FROM SALES1; -- WHAT IF DISCOUNT IS ZERO --

SELECT COUNT(ORDER_ID),ORDER_ID FROM SALES1 GROUP BY ORDER_ID;

SELECT CUSTOMER_NAME,COUNT(ORDER_ID) AS TOTAL_ORDER,SUM(SALES) AS TOTAL_SALES FROM SALES1 GROUP BY CUSTOMER_NAME;

SELECT COUNTRY,YEAR_NEW,SUM(SALES) FROM SALES1 WHERE COUNTRY = 'UNITED STATES' GROUP BY YEAR_NEW;

SELECT REGION,YEAR_NEW,SUM(SALES) FROM SALES1 GROUP BY REGION,YEAR_NEW;

SELECT COUNTRY,COUNT(Distinct CATEGORY) AS 'CATEGORY', COUNT(DISTINCT SUB_CATEGORY) AS 'SUB CATEGORY',
SUM(QUANTITY) AS 'TOTAL SALE QTY', SUM(SALES) AS 'TOTAL SALES' FROM SALES1 GROUP BY COUNTRY;

SELECT REGION,COUNT(Distinct CATEGORY) AS 'CATEGORY', COUNT(DISTINCT SUB_CATEGORY) AS 'SUB CATEGORY',
SUM(QUANTITY) AS 'TOTAL SALE QTY', SUM(SALES) AS 'TOTAL SALES' FROM SALES1 GROUP BY REGION;

SELECT STATE,COUNTRY,COUNT(Distinct CATEGORY) AS 'CATEGORY', COUNT(DISTINCT SUB_CATEGORY) AS 'SUB CATEGORY',
SUM(QUANTITY) AS 'TOTAL SALE QTY', SUM(SALES) AS 'TOTAL SALES' FROM SALES1 GROUP BY STATE, COUNTRY ORDER BY 'TOTAL SALES' DESC;