CREATE DATABASE SALES;
USE SALES;

CREATE TABLE SALES1(
	ORDER_ID VARCHAR(15) NOT NULL,
    ORDER_DATE VARCHAR(15) NOT NULL,
    SHIP_DATE VARCHAR (15) NOT NULL,
    SHIP_MODE VARCHAR(14) NOT NULL,
    CUSTOMER_NAME VARCHAR(22) NOT NULL,
    SEGMENT VARCHAR(11) NOT NULL,
    STATE VARCHAR(36) NOT NULL,
    COUNTRY VARCHAR(32) NOT NULL,
    MARKET VARCHAR(6) NOT NULL,
    REGION VARCHAR(14) NOT NULL,
    PRODUCT_ID VARCHAR(16) NOT NULL,
    CATEGORY VARCHAR(15) NOT NULL,
    SUB_CATEGORY VARCHAR(11) NOT NULL,
    PRODUCT_NAME VARCHAR(127) NOT NULL,
    SALES DECIMAL(38,0) NOT NULL,
    QUANTITY DECIMAL(38,0) NOT NULL,
    DISCOUNT DECIMAL(38,3) NOT NULL,
    PROFIT DECIMAL(38,8) NOT NULL,
    SHIPPING_COST DECIMAL(38,2) NOT NULL,
    ORDER_PRIORITY VARCHAR(8) NOT NULL,
    `YEAR` DECIMAL(38,0) NOT NULL
);

SET SESSION SQL_MODE = '';

LOAD DATA INFILE
"F:/sales_data_final.csv"      
INTO TABLE SALES1
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM SALES1;

SET SQL_SAFE_UPDATES = 0;