CREATE DATABASE SP;
USE SP;

/* SQURE_ROOT OF ANY NUMBER */
DELIMITER $$
CREATE PROCEDURE SQRT_ROOT(A INT , OUT B FLOAT)
BEGIN 
SET B = SQRT(A);
END$$
DELIMITER ;                                                        -- ALWAYS LEAVE SPACE AFTER DELIMITER THAN TYPE ;

CALL SQRT_ROOT (625,@B);
SELECT @B AS SQRT_ROOT;

SET @A =625;
CALL SQRT_ROOT(@A, @B);
SELECT @A AS NUMBER, @B AS SQRT_ROOT;

/* SQURE_ROOT OF ANY NUMBER*/
DELIMITER //
CREATE PROCEDURE CALCULATESQUAREROOT(IN A INT)
BEGIN
      DECLARE RESULT FLOAT;
      SET RESULT = SQRT(A);
      SELECT RESULT AS SQUAREROOT;
END//
DELIMITER ;

CALL CALCULATESQUAREROOT(625);

-- DROP PROCEDURE CALCULATESQUAREROOT;

/*POWER OF ANY NUMBER*/
DELIMITER $$
CREATE PROCEDURE CALCULATEPOWER(IN A FLOAT ,IN EXPONENT FLOAT, OUT RESULT FLOAT)
BEGIN
SET RESULT = POWER(A ,EXPONENT);
END$$
DELIMITER ;

CALL CALCULATEPOWER(25,2,@RESULT);
SELECT @RESULT;

SET @A = 25;
SET @EXPONENT = 2;
CALL CALCULATEPOWER(@A, @EXPONENT, @RESULT);
SELECT @A AS NUMBER, @EXPONENT AS EXPONENT, @RESULT AS POWER;

/* INOUT PROCEDURE */
DELIMITER $$ 
CREATE PROCEDURE SETCOUNTER1(INOUT COUNTER INT , IN INC INT)
BEGIN 
SET COUNTER = COUNTER + INC;
END$$ 
DELIMITER ;

SET @COUNTER = 50;
CALL SETCOUNTER1(@COUNTER, 50);
SELECT @COUNTER;

DELIMITER //
CREATE PROCEDURE USER_VAR()
BEGIN
SET @X = 15;
SET @Y = 10;
SELECT @X,@Y,@X-@Y;
END//
DELIMITER ;     

CALL USER_VAR();

-- DROP PROCEDURE USER_VAR; --

DELIMITER //
CREATE PROCEDURE USER_VAR1(IN X INT, IN Y INT)
BEGIN
SET @X = X;
SET @Y = Y;
SELECT  @X, @Y, @X - @Y;
END//
DELIMITER ;

CALL USER_VAR1(250,20);

DELIMITER //
CREATE PROCEDURE USER_VAR2()
BEGIN
     DECLARE X INT DEFAULT 15;
     DECLARE Y INT DEFAULT 10;
     DECLARE RESULT INT;
     SET RESULT = X-Y;
     SELECT X,Y,RESULT;
END//
DELIMITER ;

CALL USER_VAR2();


/* factorial */
DELIMITER $$
CREATE PROCEDURE CAL_FACTORIAL(IN number INT, OUT factorial INT)
BEGIN
DECLARE i INT DEFAULT 1;
SET factorial = 1;
WHILE i <=number DO
     SET factorial = factorial * i;
     SET i = i + 1;
END WHILE;
END$$
DELIMITER ;  
   
SET @number = 6;
call Cal_Factorial(@number,@factorial);
select @number as Number ,@factorial as factorial;

-- drop procedure CAL_FACTORIAL; --

DELIMITER $$
CREATE Function Factorial (n int) RETURNS DOUBLE
DETERMINISTIC
BEGIN
DECLARE fact DOUBLE DEFAULT 1;
DECLARE counter INT DEFAULT 1;
WHILE counter <=n DO
SET fact = fact * counter;
SET counter = counter + 1;
END WHILE;
RETURN fact;
END$$ 
delimiter  ;

SELECT  Factorial(6) AS "factorial";

## task ##
-- procedure & function --
-- /*1) BMI CALCULATION                                                            -- BMI = BODY MASS INDEX
-- BMI = WEIGHT / (HEIGHT * HEIGHT)

-- 2) CALCIUS TO FARNHIT 
-- FARNHIT = CALCIUS * (9/5) + 32. */

-- Procedure for BMI_CALCULATOR --
-- 1st Way --
DELIMITER $$
CREATE PROCEDURE BMI_CALCULATOR(IN WEIGHT DECIMAL(5,2),IN HEIGHT DECIMAL(5,2), OUT BMI DECIMAL(5,2))
BEGIN
SELECT 
HEIGHT, WEIGHT, WEIGHT / (HEIGHT * HEIGHT) AS BMI;
END$$
DELIMITER ;

CALL BMI_CALCULATOR(106,1.77,@x);
-- 2nd Way --
DELIMITER $$
CREATE PROCEDURE BMI_CALCULATOR_2(IN Weight FLOAT, IN Height FLOAT, OUT BMI DECIMAL(10,2))
BEGIN 
SET BMI = weight / (height * height);
END$$
DELIMITER ;

CALL BMI_CALCULATOR_2(106, 1.77, @BMI);
SELECT @bmi AS BMI;

-- Create Function to Calculate BMI --
DELIMITER $$
CREATE FUNCTION Calculate_BMI (Weight DECIMAL(5,2),HEIGHT DECIMAL(5,2)) RETURNS DECIMAL(5,2)
DETERMINISTIC
BEGIN
DECLARE BMI DECIMAL (5,2);
SET BMI = weight / (height * height);
RETURN BMI;
END$$
DELIMITER ;

SELECT Calculate_BMI(106,1.77) AS BMI;

-- Procedure For Celcius to Fahrenheit --
DELIMITER $$
CREATE PROCEDURE ConvertCelsiusToFahrenheit(IN celsius DECIMAL(5,2), OUT fahrenheit DECIMAL(5,2))
BEGIN 
SELECT Celsius, (celsius * 9/5) + 32 AS Fahrenheit;
END$$
DELIMITER ;

CALL ConvertCelsiusToFahrenheit (37, @fahrenheit);

-- Function For Celcius to Fahrenheit --
DELIMITER $$
CREATE FUNCTION ConvertCelsiusToFahrenheit(Celsius DECIMAL(5,2)) RETURNS DECIMAL (5,2)
DETERMINISTIC
BEGIN
DECLARE Fahrenheit DECIMAL (5,2);
SET Fahrenheit = (Celsius * 9/5) + 32;
RETURN Fahrenheit;
END $$
DELIMITER ;

SELECT ConvertCelsiusToFahrenheit (40.50) AS Fahrenheit;

-- CREATE PROCEDURE FOR BMI CALCULATOR WITH CATEGORY --
DELIMITER $$
CREATE PROCEDURE CalculateBMIwithCategory(IN Weight FLOAT, IN Height FLOAT, OUT BMI DECIMAL(5,2),OUT CATEGORY VARCHAR(20))
BEGIN
SET BMI = weight / (height * height);
IF BMI < 18.5 THEN 
SET CATEGORY = 'UnderWeight';
ELSEIF BMI >= 18.5 AND BMI < 24.9 THEN 
SET CATEGORY = 'Normal Weight';
ELSEIF BMI >= 25 AND BMI < 29.9 THEN 
SET CATEGORY = 'Overweight';
ELSE 
SET CATEGORY = 'Obesity';
END IF;
END$$
DELIMITER ;

SET @WEIGHT = 70;
SET @HEIGHT = 1.86;
CALL CalculateBMIwithCategory(@WEIGHT,@HEIGHT,@BMI,@CATEGORY);
SELECT @WEIGHT AS WEIGHT,@HEIGHT AS HEIGHT, @BMI AS BMI,@CATEGORY AS CATEGORY;

-- REVERSE A STRING--
DELIMITER $$
CREATE PROCEDURE REVERSEDSTRING(IN INPUTSTRING VARCHAR(255), OUT REVERSEDSTRING VARCHAR(255))
BEGIN
DECLARE I INT DEFAULT 1;
DECLARE LEN INT;
DECLARE TEMPSTRING VARCHAR(255) DEFAULT '';
SET LEN = LENGTH(INPUTSTRING);                     
WHILE I <= LEN DO
SET TEMPSTRING = CONCAT(SUBSTRING(INPUTSTRING, I, 1), TEMPSTRING);
SET I = I + 1;
END WHILE;
SET REVERSEDSTRING = TEMPSTRING;
END$$
DELIMITER ;

SET @INPUTSTRING = 'TIRTH MODI';
CALL REVERSEDSTRING(@INPUTSTRING, @REVERSEDSTRING);
SELECT @INPUTSTRING AS `INPUT STRING`, @REVERSEDSTRING AS `REVERSED STRING`;

-- ADD Days to a Date --
Delimiter $$
CREATE PROCEDURE ADDDAYSTODATE(IN INPUTDATE DATE,IN DAYSTOADD INT, OUT NEWDATE DATE)
BEGIN
SET NEWDATE = DATE_ADD(INPUTDATE, INTERVAL DAYSTOADD DAY);
END$$
DELIMITER ;

CALL ADDDAYSTODATE ('2026-07-15',17, @NEWDATE);
SELECT @NEWDATE;

CALL ADDDAYSTODATE (CURRENT_DATE,3, @NEWDATE);
SELECT @NEWDATE;

-- ADD Years to a Date --
DELIMITER $$
CREATE PROCEDURE ADDYEARSTODATE (IN INPUTDATE DATE ,IN YEARSTOADD INT,OUT NEWDATE DATE)
BEGIN
SET NEWDATE = DATE_ADD(INPUTDATE, INTERVAL YEARSTOADD YEAR);
END$$
DELIMITER ;

CALL ADDYEARSTODATE('2025-05-07',5,@NEWDATE);
SELECT @NEWDATE;

-- Add Months to a Date --
DELIMITER $$
CREATE PROCEDURE ADDMONTHTODATE(IN INPUTDATE DATE, IN MONTHTOADD INT, OUT NEWDATE DATE)
BEGIN 
SET NEWDATE = DATE_ADD(INPUTDATE, INTERVAL MONTHTOADD MONTH);
END$$
DELIMITER ;

CALL ADDMONTHTODATE('2026-07-15', 6, @NEWDATE);
SELECT @NEWDATE;

-- ADD Minutes to Time --
DELIMITER $$
CREATE PROCEDURE ADDMINUTESTOTIME(IN INPUTTIME TIME, IN MINUTESTOADD INT, OUT NEWTIME TIME)
BEGIN 
SET NEWTIME = ADDTIME(INPUTTIME, SEC_TO_TIME(MINUTESTOADD * 60));
END$$
DELIMITER ;

CALL ADDMINUTESTOTIME('10:23:00',37,@NEWTIME);
SELECT @NEWTIME;

-- ADD HOURS TO TIME --
DELIMITER $$
CREATE PROCEDURE ADDHOURSTOTIME(IN INPUTTIME TIME,IN HOURSTOADD INT,OUT NEWTIME TIME)
BEGIN
SET NEWTIME = ADDTIME(INPUTTIME,SEC_TO_TIME(HOURSTOADD*3600));
END$$
DELIMITER ;

CALL ADDHOURSTOTIME ('10:51:00',10,@NEWTIME);
SELECT @NEWTIME;

-- DATE DIFFERENCE --
DELIMITER $$
CREATE PROCEDURE DATEDIFFERENCE(IN STARTDATE DATE, IN ENDDATE DATE, OUT DIFF INT)
BEGIN
SET DIFF = DATEDIFF(ENDDATE,STARTDATE);
END$$
DELIMITER ;

CALL DATEDIFFERENCE('2026-07-15','2026-12-31',@DIFF);
SELECT @DIFF AS DIFF;

-- YEAR DIFFERENCE with month --
DELIMITER $$
CREATE PROCEDURE YEARDIFFERENCE(IN STARTDATE DATE,IN ENDDATE DATE, DIFF VARCHAR(20))
BEGIN 
DECLARE YEAR_DIFF INT;
DECLARE MONTH_DIFF INT;
DECLARE TOTAL_MONTH_DIFF INT;
SET YEAR_DIFF = YEAR(ENDDATE) - YEAR(STARTDATE);
SET MONTH_DIFF = MONTH(ENDDATE) - MONTH(STARTDATE);
SET TOTAL_MONTH_DIFF = (YEAR_DIFF * 12) + MONTH_DIFF;
SET DIFF = CONCAT(YEAR_DIFF, ' YEAR ', MOD(TOTAL_MONTH_DIFF,12), ' MONTH');
END$$
DELIMITER ;

CALL YEARDIFFERENCE('1995-01-01',CURRENT_DATE(),@DIFF);
SELECT @DIFF AS AGE;

-- YEAR DIFFERENCE WITH MONTH AND DAYS --
DELIMITER $$
CREATE PROCEDURE AGEDIFFERENCE(IN STARTDATE DATE, IN ENDDATE DATE, OUT DIFF VARCHAR(30))
BEGIN
DECLARE YEAR_DIFF INT;
DECLARE MONTH_DIFF INT;
DECLARE DAY_DIFF INT;
SET YEAR_DIFF = TIMESTAMPDIFF(YEAR, STARTDATE,ENDDATE);
SET MONTH_DIFF = TIMESTAMPDIFF(MONTH,DATE_ADD(STARTDATE,INTERVAL YEAR_DIFF YEAR), ENDDATE);
SET DAY_DIFF =  DATEDIFF(ENDDATE,DATE_ADD(DATE_ADD(STARTDATE,INTERVAL YEAR_DIFF YEAR),INTERVAL MONTH_DIFF MONTH));
SET DIFF = CONCAT(YEAR_DIFF, ' YEAR ', MONTH_DIFF, ' MONTH ', DAY_DIFF, ' DAY');
END$$
DELIMITER ;

CALL AGEDIFFERENCE('1995-01-01',CURRENT_DATE(),@DIFF);
SELECT @DIFF AS AGE;

-- Updating Salary in a Table --
CREATE TABLE EMPLOYEES(ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(30),SALARY DECIMAL(10,2));
INSERT INTO EMPLOYEES (NAME,SALARY) 
VALUES ('TIRTH MODI',50000.00),('Anil Soni',30000.00);

SELECT * FROM EMPLOYEES;

DELIMITER $$
CREATE PROCEDURE UPDATESALARY(IN EMPLOYEEID INT,IN NEWSALARY DECIMAL(10,2))
BEGIN 
UPDATE employees  SET SALARY = NEWSALARY WHERE ID = EMPLOYEEID;
SELECT * FROM EMPLOYEES;
END$$
DELIMITER ;

CALL UPDATESALARY (1,55000);

-- INSERT AND RETRIEVE DATA --
CREATE TABLE SAMPLETABLE (ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255),AGE INT);

DELIMITER $$
CREATE PROCEDURE INSERTRECORD(IN InName VARCHAR(255),IN InAGE INT)
BEGIN
INSERT INTO SAMPLETABLE (NAME, AGE) VALUES (InName, InAge);
SELECT * FROM SAMPLETABLE;
END$$
DELIMITER ; 

CALL INSERTRECORD ('Darshan',29);

-- RETRIEVE INSERTED RECORD --
DELIMITER $$
CREATE PROCEDURE RETRIEVERECORD(IN RECORDID INT, OUT OutName VARCHAR(255),OUT OutAge INT)
BEGIN 
SELECT NAME,AGE INTO OutName, OutAge FROM SAMPLETABLE WHERE ID = RECORDID;
END$$
DELIMITER ;

CALL RETRIEVERECORD(1,@NAME,@AGE);
SELECT @NAME, @AGE;

DELIMITER $$
CREATE PROCEDURE RETRIEVERECORD_1(IN InName VARCHAR(255), OUT OutID INT, OUT OutName VARCHAR(255), OUT OutAge INT)
BEGIN 
SELECT ID,NAME,AGE INTO OutID,OutName, OutAge FROM SAMPLETABLE WHERE NAME = InName ;
END$$
DELIMITER ;

CALL RETRIEVERECORD_1('Darshan',@OUTID,@OUTNAME,@OUTAGE);
SELECT @OUTID AS ID ,@OUTNAME AS Name ,@OUTAGE AS AGE;

-- SUM OF NUMBERS IN A RANGE --
DELIMITER $$
CREATE PROCEDURE SUMRANGE(IN STARTNUM INT,IN ENDNUM INT, OUT TOTAL INT)
BEGIN 
DECLARE I INT DEFAULT STARTNUM;
SET TOTAL = 0;
WHILE I <= ENDNUM DO
SET TOTAL = TOTAL + I;
SET I = I + 1;
END WHILE;
END$$
DELIMITER ;

CALL SUMRANGE(1,5,@TOTAL);
SELECT @TOTAL AS TOTAL;

-- CONDITIONAL LOGIC PROCEDURE --
DELIMITER $$
CREATE PROCEDURE CHECKAGE(IN AGE INT, OUT CATEGORY VARCHAR(50))
BEGIN
IF AGE < 13 THEN SET CATEGORY = 'CHLID';
ELSEIF AGE BETWEEN 13 AND 19 THEN SET CATEGORY = 'TEENAGER';
ELSEIF AGE BETWEEN 20 AND 64 THEN SET CATEGORY = 'ADULT';
ELSE SET CATEGORY = 'SENIOR';
END IF;
END$$
DELIMITER ;

CALL CHECKAGE (19, @CATEGORY);
SELECT @CATEGORY;

-- Procedure for Handling Transactions with Rollback --
CREATE TABLE ACCOUNTS (ACCOUNT_ID INT AUTO_INCREMENT PRIMARY KEY, ACCOUNT_NAME VARCHAR(255),BAlANCE DECIMAL(10,2));
INSERT INTO ACCOUNTS (ACCOUNT_NAME, BALANCE) VALUES ('Account 1',500.00),('Account 2',300.00);

SELECT * FROM ACCOUNTS;

DELIMITER $$
CREATE PROCEDURE TRANSFERFUNDS(IN FROMACCOUNT INT, IN TOACCOUNT INT,IN AMOUNT DECIMAL(10,2))
BEGIN
DECLARE CURRENTBALANCE DECIMAL(10,2);
START TRANSACTION;
SELECT BALANCE INTO CURRENTBALANCE FROM ACCOUNTS WHERE ACCOUNT_ID = FROMACCOUNT;
IF CURRENTBALANCE >= AMOUNT THEN
UPDATE ACCOUNTS SET BALANCE = BALANCE - AMOUNT WHERE ACCOUNT_ID = FROMACCOUNT;
UPDATE ACCOUNTS SET BALANCE = BALANCE + AMOUNT WHERE ACCOUNT_ID = TOACCOUNT;
COMMIT;
ELSE
ROLLBACK;
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Insufficient Balance';
END IF;
SELECT * FROM ACCOUNTS;
END$$
DELIMITER ; 

SELECT * FROM ACCOUNTS;
CALL TRANSFERFUNDS(1,2,400);
CALL TRANSFERFUNDS(2,1,300);
CALL TRANSFERFUNDS(1,2,600);  -- THIS WILL GIVE ERROR FOR 'INSUFFICIENT FUNDS' --

-------------------------------

-- Loop and Cursor Example --
CREATE TEMPORARY TABLE IF NOT EXISTS TEMPEVENNUMBERS ( 
EVENNUMBER INT 
);

DELIMITER $$
CREATE PROCEDURE LISTEVENNUMBERS(IN STARTNUM INT, IN ENDNUM INT)
BEGIN
	DECLARE CURRENT INT DEFAULT STARTNUM;
	TRUNCATE TABLE TEMPEVENNUMBERS;
	WHILE CURRENT <= ENDNUM DO
		IF CURRENT % 2 = 0 THEN
			INSERT INTO TEMPEVENNUMBERS (EVENNUMBER) VALUES (CURRENT);
		END IF;
		SET CURRENT = CURRENT + 1;
	END WHILE;
	SELECT EVENNUMBER FROM TEMPEVENNUMBERS;
END$$
DELIMITER ; 

CALL LISTEVENNUMBERS(55, 75);

-- STRING CONCATENATION --
DELIMITER $$
CREATE PROCEDURE CONCATENATESTRINGS(IN STR1 VARCHAR(255), IN STR2 VARCHAR(255), OUT RESULT VARCHAR(255))
BEGIN 
SET RESULT = CONCAT(STR1,' ',STR2);
END$$
DELIMITER ;

CALL CONCATENATESTRINGS('Tirth','Modi',@RESULT);
SELECT @RESULT AS CONCAT_STRING;

-- Cursor Example --
CREATE TABLE STUDENTS (ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255),SCORE INT);
INSERT INTO STUDENTS (NAME, SCORE) VALUES ('Tirth', 85),('Rahul',92),('Prakash',78);

DELIMITER $$
CREATE PROCEDURE ITERATESTUDENTS()
BEGIN 
DECLARE STUDENT_NAME VARCHAR(255);
DECLARE STUDENT_SCORE INT;
DECLARE DONE INT DEFAULT FALSE;
DECLARE CURSOR1 CURSOR FOR SELECT NAME, SCORE FROM STUDENTS;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
OPEN CURSOR1;
read_loop: LOOP
FETCH CURSOR1 INTO STUDENT_NAME,STUDENT_SCORE;
IF DONE THEN LEAVE read_loop;
END IF;
SELECT STUDENT_NAME,STUDENT_SCORE;
END LOOP;
CLOSE CURSOR1;
END$$
DELIMITER ; 

SELECT * FROM STUDENTS;

CALL ITERATESTUDENTS();

-- DATA VALIDATION --
CREATE TABLE USER1 (
USER_ID INT AUTO_INCREMENT PRIMARY KEY,
USERNAME VARCHAR(50) UNIQUE,
EMAIL VARCHAR (100)
);

DELIMITER $$
CREATE PROCEDURE VALIDATEANDINSERTUSER(IN IN_USERNAME VARCHAR(50),IN IN_EMAIL VARCHAR(100))
BEGIN
DECLARE USERNAME_EXISTS INT DEFAULT 0;
DECLARE EMAIL_EXISTS INT DEFAULT 0;
SELECT COUNT(*) INTO USERNAME_EXISTS FROM USER1 WHERE USERNAME = IN_USERNAME;
SELECT COUNT(*) INTO EMAIL_EXISTS FROM USER1 WHERE EMAIL = IN_EMAIL;
IF USERNAME_EXISTS > 0 THEN
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Username already exists';
ELSEIF EMAIL_EXISTS > 0 THEN
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Email already exists';
ELSE 
INSERT INTO USER1 (USERNAME, EMAIL) VALUES (IN_USERNAME, IN_EMAIL);
END IF;
END$$
DELIMITER ;

SELECT * FROM USER1;

INSERT INTO USER1 (USERNAME, EMAIL)
VALUES
('Darshan', 'darshan@gmail.com'),
('Tirth', 'tirth.patel@gmail.com'),
('Anil', 'anil.shah@gmail.com'),
('Priya', 'priya.mehta@gmail.com'),
('Neha', 'neha.patel@gmail.com');

-- Should insert successfully --
CALL VALIDATEANDINSERTUSER('Rahul', 'rahul@gmail.com');
-- Duplicate username --
CALL VALIDATEANDINSERTUSER('Darshan', 'darshan2@gmail.com');
-- Duplicate email --
CALL VALIDATEANDINSERTUSER('Amit', 'darshan@gmail.com');
-- Both username and email already exist --
CALL VALIDATEANDINSERTUSER('Priya', 'priya.mehta@gmail.com');

-- Complex Query --
CREATE TABLE CUSTOMERS (
CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY, 
CUSTOMER_NAME VARCHAR(100)
);

CREATE TABLE ORDERS (
ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
CUSTOMER_ID INT,
ORDER_DATE DATE,
AMOUNT DECIMAL(10,2),
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMERS (CUSTOMER_ID)
);
SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;

INSERT INTO CUSTOMERS (CUSTOMER_NAME) VALUES ('Tirth'),('Prakash');
INSERT INTO ORDERS (CUSTOMER_ID,ORDER_DATE, AMOUNT) VALUES (1, '2024-06-01', 150.00),(2, '2024-06-05', 200.00);

INSERT INTO CUSTOMERS (CUSTOMER_NAME) VALUES ('Keyur'),('Maulik');
INSERT INTO ORDERS (CUSTOMER_ID,ORDER_DATE, AMOUNT) VALUES (3, '2024-07-10', 600.00),(2, '2024-07-15', 1000.00);

DELIMITER $$
CREATE PROCEDURE GETORDERDETAILS()
BEGIN
SELECT O.ORDER_ID, C.CUSTOMER_NAME, O.ORDER_DATE, O.AMOUNT
FROM ORDERS O
JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID;
END$$
DELIMITER ;

-- SAME PROCEDURE USING WHERE INSTEAD OF JOIN --
DELIMITER $$
CREATE PROCEDURE GETORDERDETAILS()
BEGIN
SELECT O.ORDER_ID, C.CUSTOMER_NAME, O.ORDER_DATE, O.AMOUNT
FROM ORDERS O, CUSTOMERS C WHERE O.CUSTOMER_ID = C.CUSTOMER_ID;
END$$
DELIMITER ;

SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;

CALL GETORDERDETAILS();

-- SAME PROCEDURE BUT AMOUNT GETS ADDED FOR EACH ENTRY --
DELIMITER $$
CREATE PROCEDURE GETORDERDETAILS2()
BEGIN
DECLARE cumulative_sum DECIMAL(10,2) DEFAULT 0;
SELECT O.ORDER_ID, C.CUSTOMER_NAME, O.ORDER_DATE, O.AMOUNT, 
	   @Cumulative_Sum := @Cumulative_Sum + O.Amount AS `Total Sales`
FROM ORDERS O
JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
CROSS JOIN (SELECT @Cumulative_Sum := 0) AS dummy
ORDER BY O.ORDER_DATE, O.ORDER_ID;
END$$
DELIMITER ; 

INSERT INTO CUSTOMERS (CUSTOMER_NAME) VALUES ('AMAN');
INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, AMOUNT) VALUES (5,'2025-12-11',2000.00);

CALL GETORDERDETAILS2();

-- Error Handling --
DELIMITER $$
CREATE PROCEDURE DIVIDENUMBERS (IN NUM1 DECIMAL(10,2), IN NUM2 DECIMAL(10,2), OUT RESULT DECIMAL(10,2))
BEGIN
DECLARE DIVIDE_BY_ZERO CONDITION FOR SQLSTATE '22012';
DECLARE CONTINUE HANDLER FOR DIVIDE_BY_ZERO
BEGIN 
SET RESULT = NULL;
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Division by Zero is not allowed';
END;
IF NUM2 = 0 THEN
SIGNAL SQLSTATE '22012' SET MESSAGE_TEXT = 'Division by Zero';
ELSE 
SET RESULT = NUM1 / NUM2;
END IF;
END$$
DELIMITER ;

CALL DIVIDENUMBERS(10,0,@RESULT);

CALL DIVIDENUMBERS(10,2,@RESULT);
SELECT @RESULT;